import { Err, Ok, Result } from "ts-results";

type Errors = "InitError"
            | "InvalidReservablePackage" 
            | "WrongStepInDeliverySequence" 
            | "UserAlreadyCurrentHolder"
            | "UserNotFound"
            | "DeliveryStepNotAdded"
            | "DeliveryStepNotFound"
            | "DeliveryStepNotInitialized"
            | "DeliveryStepNotYetAccepted"
            | "InvalidUser"
            | "SenderCantBeReserver"
            | "SenderCantBeDispatcher"
            | "ReserverNotFound" 
            | "ReserverAlreadySelected" 
            | "ReceiverCantBeReserver"
            | "ReceiverCantBeDispatcher"
            | "UserAlreadyADispatcher"
            | "InvalidSender"
            | "InvalidRecipient"
            | "UserNotCurrentHolder"
            | "InvalidDbType"
            
type OkMessage = "ReserverAdded"
            | "ReserverRemoved"
            | "CurrentHolderSet"
            | "DeliveryStepAdded"
            | "ReserveRequestRejected"
            | "ReserveRequestAccepted"
            | "DeliveryStepInitialized"
            | "DeliveryRequestAccepted"
            | "DeliveryRequestRejected"
            | "PackagePickedUp"
            | "PackageDelivered"
            | "PackageDispatched"
            | "DbCreated"

export {Errors, Err, Ok, Result, OkMessage};